language: haskell
matrix:
- ghc: 7.4.2
  cabal-install: 1.16
- ghc: 7.6.3
  cabal-install: 1.16
- ghc: 7.8.4
  cabal-install: 1.18
- ghc: 7.10.3
  cabal-install: 1.22
- ghc: 8.0.2
  cabal-install: 1.24
- ghc: 8.2.2
  cabal-install: 2.0
- ghc: 8.4.2
  cabal-install: 2.2
script:
- cabal configure && cabal build
