# NB: don't set `language: haskell` here

sudo: false

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.2

addons:
  apt:
    sources:
    - hvr-ghc

addons:
  apt:
    packages:
    - ghc-$GHCVER

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - echo "$(ghc --version)"
 - ghc Setup

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - ./Setup configure
 - ./Setup build
